name: Unit_Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
          pipreqs $GITHUB_WORKSPACE/folder
          pip install -r $GITHUB_WORKSPACE/folder/requirements.txt          
      - name: Test
        run:
          python -m unittest discover -v -s $GITHUB_WORKSPACE/folder